# Generated by Django 6.0.3 on 2026-03-06 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Q1FieldTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='項目名')),
                ('order', models.IntegerField(default=0, verbose_name='表示順')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
            ],
            options={
                'verbose_name': 'Q1テンプレート',
                'verbose_name_plural': 'Q1テンプレート',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='セクションタイトル')),
                ('section_type', models.CharField(choices=[('radio_matrix', 'ラジオマトリクス'), ('free_text', '自由記述'), ('select', '選択式')], max_length=20, verbose_name='タイプ')),
                ('scale_labels', models.JSONField(blank=True, default=list, verbose_name='選択肢ラベル')),
                ('placeholder', models.CharField(blank=True, max_length=200, verbose_name='プレースホルダー')),
                ('order', models.IntegerField(default=0, verbose_name='表示順')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
            ],
            options={
                'verbose_name': '質問セクション',
                'verbose_name_plural': '質問セクション',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='項目名')),
                ('order', models.IntegerField(default=0, verbose_name='表示順')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reports.questionsection')),
            ],
            options={
                'verbose_name': '質問項目',
                'verbose_name_plural': '質問項目',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(verbose_name='週開始日（月曜）')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提出日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '週報',
                'verbose_name_plural': '週報',
                'ordering': ['-week_start'],
                'unique_together': {('user', 'week_start')},
            },
        ),
        migrations.CreateModel(
            name='Q1ProjectField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='項目名')),
                ('value', models.TextField(blank=True, verbose_name='値')),
                ('order', models.IntegerField(default=0, verbose_name='表示順')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q1_fields', to='reports.weeklyreport')),
            ],
            options={
                'verbose_name': 'Q1フィールド',
                'verbose_name_plural': 'Q1フィールド',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, verbose_name='回答値')),
                ('question_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.questionitem')),
                ('question_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.questionsection')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='reports.weeklyreport')),
            ],
            options={
                'verbose_name': '回答',
                'verbose_name_plural': '回答',
            },
        ),
    ]
