# Generated by Django 6.0.3 on 2026-03-06 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.questionitem'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('report', 'question_section', 'question_item')},
        ),
    ]
