# Generated by Django 6.0.3 on 2026-05-18 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_answer_question_item_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OneOnOneQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_number', models.IntegerField(verbose_name='セクション番号')),
                ('section_title', models.CharField(max_length=100, verbose_name='セクション名')),
                ('question_text', models.CharField(max_length=200, verbose_name='質問文')),
                ('hint_text', models.CharField(blank=True, default='', max_length=200, verbose_name='補足テキスト')),
                ('order', models.IntegerField(default=0, verbose_name='表示順')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
            ],
            options={
                'verbose_name': '1on1質問',
                'verbose_name_plural': '1on1質問',
                'ordering': ['section_number', 'order'],
            },
        ),
        migrations.CreateModel(
            name='OneOnOneSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conducted_at', models.DateField(verbose_name='実施日')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oneone_interviews', to=settings.AUTH_USER_MODEL, verbose_name='担当管理者')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oneone_sessions', to=settings.AUTH_USER_MODEL, verbose_name='メンバー')),
            ],
            options={
                'verbose_name': '1on1セッション',
                'verbose_name_plural': '1on1セッション',
                'ordering': ['-conducted_at'],
            },
        ),
        migrations.CreateModel(
            name='OneOnOneAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='回答')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.oneononequestion', verbose_name='質問')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='reports.oneononesession', verbose_name='セッション')),
            ],
            options={
                'verbose_name': '1on1回答',
                'verbose_name_plural': '1on1回答',
            },
        ),
    ]
