# Generated by Django 6.0.3 on 2026-05-18 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_oneononequestion_oneononesession_oneononeanswer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='oneononeanswer',
            unique_together={('session', 'question')},
        ),
    ]
